// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoRxKDXWysJz3CS-ag5PuxW_39uklekY',
    appId: '1:1054004814540:web:fbec6e2cf74fe2ffe11869',
    messagingSenderId: '1054004814540',
    projectId: 'jan-arogya',
    authDomain: 'jan-arogya.firebaseapp.com',
    storageBucket: 'jan-arogya.firebasestorage.app',
    measurementId: 'G-FH6DM4MMPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlplk1LBYzsiATY10m2jz9tBSjNLMNyVU',
    appId: '1:1054004814540:android:206422107455d809e11869',
    messagingSenderId: '1054004814540',
    projectId: 'jan-arogya',
    storageBucket: 'jan-arogya.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnynT4UtPgxAwAzxLk4PCAPWb7Rs-BkAY',
    appId: '1:1054004814540:ios:b959f20c07d753c5e11869',
    messagingSenderId: '1054004814540',
    projectId: 'jan-arogya',
    storageBucket: 'jan-arogya.firebasestorage.app',
    androidClientId: '1054004814540-pn0tek5e80sba5qoe0rnfrs87t9u4bnu.apps.googleusercontent.com',
    iosClientId: '1054004814540-h6qm5lnuf68g27qdjuaa3dbj5gl21sb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.janArogyaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnynT4UtPgxAwAzxLk4PCAPWb7Rs-BkAY',
    appId: '1:1054004814540:ios:b959f20c07d753c5e11869',
    messagingSenderId: '1054004814540',
    projectId: 'jan-arogya',
    storageBucket: 'jan-arogya.firebasestorage.app',
    androidClientId: '1054004814540-pn0tek5e80sba5qoe0rnfrs87t9u4bnu.apps.googleusercontent.com',
    iosClientId: '1054004814540-h6qm5lnuf68g27qdjuaa3dbj5gl21sb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.janArogyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLoRxKDXWysJz3CS-ag5PuxW_39uklekY',
    appId: '1:1054004814540:web:218e52ea8a16b336e11869',
    messagingSenderId: '1054004814540',
    projectId: 'jan-arogya',
    authDomain: 'jan-arogya.firebaseapp.com',
    storageBucket: 'jan-arogya.firebasestorage.app',
    measurementId: 'G-VKJSW8GN7V',
  );
}
